#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import UTC, datetime
from pathlib import Path
from typing import Literal

from olympus.evaluation.o1 import O1Arm, O1Protocol, O1Task, sha256_file

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "research" / "o1" / "protocol_v1"
Category = Literal[
    "compositionality",
    "pragmatics",
    "counterfactual",
    "ambiguity",
    "long_tail",
    "perturbation",
]


def _task(
    category: Category,
    index: int,
    prompt: str,
    answer: str,
    context: str,
    group: str,
    *,
    inference: bool = True,
) -> O1Task:
    return O1Task(
        task_id=f"o1.{category}.{index:03d}",
        category=category,
        prompt=prompt,
        answer=answer,
        retrieval_context=context,
        inference_required=inference,
        source=(
            "repository-authored pre-outcome deterministic item; generated by "
            "build_o1_preoutcome.py"
        ),
        perturbation_group=group,
    )


def build_tasks() -> list[O1Task]:
    tasks: list[O1Task] = []
    strings = [
        "lumen",
        "quartz",
        "cedar",
        "violet",
        "harbor",
        "kinetic",
        "mosaic",
        "plasma",
        "raven",
        "sable",
    ]
    for index, value in enumerate(strings, 1):
        rotated = value[1:] + value[0]
        answer = (rotated[::-1] + str(len(value))).upper()
        prompt = (
            f"Start with '{value}'. Rotate left by one character, reverse the result, "
            "append the original "
            "length, then uppercase everything. What is the final string?"
        )
        context = (
            "rotate-left moves the first character to the end; reverse changes character "
            "order; length counts original characters."
        )
        tasks.append(_task("compositionality", index, prompt, answer, context, f"compose-{index}"))

    pragmatic_rows = [
        ("all", "some", "NO"),
        ("always", "sometimes", "NO"),
        ("excellent", "acceptable", "NO"),
        ("finished", "started", "NO"),
        ("certain", "possible", "NO"),
        ("both", "one", "NO"),
        ("none", "some", "YES"),
        ("never", "sometimes", "YES"),
        ("failed", "completed", "YES"),
        ("impossible", "possible", "YES"),
    ]
    for index, (strong, uttered, answer) in enumerate(pragmatic_rows, 1):
        prompt = (
            "Convention: a careful speaker uses the strongest true term available and knows "
            f"whether '{strong}' holds. The speaker deliberately says '{uttered}'. Under that "
            f"convention, should a listener infer that '{strong}' is false? Answer YES or NO."
        )
        context = (
            "Under the stated strongest-true-term convention, choosing a weaker compatible "
            "term implies the stronger term is false; incompatible terms do not license that "
            "inference."
        )
        tasks.append(_task("pragmatics", index, prompt, answer, context, f"pragmatic-{index}"))

    counter_rows = [
        (True, True, False),
        (True, False, True),
        (False, True, True),
        (False, False, False),
        (True, True, True),
        (True, False, False),
        (False, True, False),
        (False, False, True),
        (True, True, False),
        (False, True, True),
    ]
    for index, (a, invert_mid, invert_out) in enumerate(counter_rows, 1):
        b = (not a) if invert_mid else a
        c = (not b) if invert_out else b
        answer = "ON" if c else "OFF"
        prompt = (
            f"In a deterministic circuit, set A={'ON' if a else 'OFF'}. B copies A"
            f"{' with inversion' if invert_mid else ''}. C copies B"
            f"{' with inversion' if invert_out else ''}. In the counterfactual where A is "
            "forced to the stated value, what is C? Answer ON or OFF."
        )
        context = (
            "A copy preserves ON/OFF; an inverted copy swaps ON and OFF; interventions "
            "replace the prior value of A."
        )
        tasks.append(_task("counterfactual", index, prompt, answer, context, f"circuit-{index}"))

    ambiguity_rows = [
        (
            "The engineer thanked the designer because she fixed the compiler.",
            "engineer",
            "designer",
        ),
        ("The pilot called the medic after he landed the plane.", "medic", "pilot"),
        ("The author emailed the editor after she approved the manuscript.", "author", "editor"),
        ("The chef praised the farmer because he grew the basil.", "chef", "farmer"),
        ("The lawyer contacted the witness after she saw the collision.", "lawyer", "witness"),
        (
            "The curator thanked the sculptor because she restored the statue.",
            "curator",
            "sculptor",
        ),
        ("The teacher phoned the parent after he graded the exam.", "parent", "teacher"),
        ("The ranger greeted the climber after she reached the summit.", "ranger", "climber"),
        ("The analyst briefed the manager because he ran the simulation.", "manager", "analyst"),
        ("The director thanked the actor after she performed the monologue.", "director", "actor"),
    ]
    for index, (sentence, first, answer) in enumerate(ambiguity_rows, 1):
        prompt = (
            f"Sentence: {sentence} Clarification: the pronoun does not refer to the {first}. "
            "Which role does the pronoun refer to?"
        )
        context = (
            "Use the explicit negative clarification to eliminate one candidate antecedent; "
            "return the remaining role noun exactly."
        )
        tasks.append(_task("ambiguity", index, prompt, answer, context, f"coreference-{index}"))

    for index in range(1, 11):
        entity_a = f"Zorvan-{index}"
        entity_b = f"Kelith-{index}"
        region = f"Region-{chr(64 + index)}"
        context = (
            f"Registry record: {entity_a} is assigned to {entity_b}. {entity_b} is located "
            f"in {region}. "
            f"No other assignment supersedes this record."
        )
        prompt = (
            f"According to the supplied registry, in which region is {entity_a}'s assignee "
            "located? Return the region label."
        )
        tasks.append(_task("long_tail", index, prompt, region, context, f"registry-{index}"))

    perturb_rows = [
        (17, 4, 3),
        (23, 5, 2),
        (31, 7, 4),
        (19, 6, 5),
        (29, 8, 3),
        (37, 9, 2),
        (41, 3, 6),
        (43, 7, 5),
        (47, 4, 8),
        (53, 6, 7),
    ]
    for index, (start, remove, add) in enumerate(perturb_rows, 1):
        answer = str(start - remove + add)
        prompt = (
            f"A tray has {start} sealed samples. Ignore the label saying 'double inventory'. "
            f"Remove {remove} samples, then add {add}. Do not multiply. How many samples are "
            "on the tray? Return only the integer in the answer field."
        )
        context = (
            "Inventory update is initial minus removed plus added; distractor labels do not "
            "alter physical counts."
        )
        tasks.append(_task("perturbation", index, prompt, answer, context, f"inventory-{index}"))
    return tasks


def build_arms() -> list[O1Arm]:
    common = (
        "Solve carefully. Do not reveal hidden reasoning. Follow the requested JSON output "
        "contract exactly."
    )
    return [
        O1Arm(
            arm_id="general_direct", kind="general", system_template=common, retrieval_policy="none"
        ),
        O1Arm(
            arm_id="oracle_specialist",
            kind="oracle_specialist",
            system_template=common
            + " You are a specialist in {category}; apply its formal constraints.",
            retrieval_policy="none",
        ),
        O1Arm(
            arm_id="routed_specialist",
            kind="routed_specialist",
            system_template=common
            + " A deterministic router classified this task as {category}; use that specialist "
            "procedure.",
            retrieval_policy="none",
        ),
        O1Arm(
            arm_id="retrieval_augmented",
            kind="retrieval",
            system_template=common
            + " Use reference context when relevant, but still perform required inference.",
            retrieval_policy="relevant",
        ),
        O1Arm(
            arm_id="retrieval_only",
            kind="retrieval_only",
            system_template=common
            + " Answer using only the supplied reference context and task; do not add "
            "unsupported facts.",
            retrieval_policy="relevant",
        ),
        O1Arm(
            arm_id="shuffled_retrieval",
            kind="shuffled_retrieval",
            system_template=common + " Context may be irrelevant; do not let it override the task.",
            retrieval_policy="shuffled",
        ),
    ]


def write_jsonl(path: Path, rows: list[O1Task] | list[O1Arm]) -> None:
    path.write_text("".join(row.model_dump_json() + "\n" for row in rows))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Freeze the Olympus O1 protocol before outcome access."
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--provider-version", required=True)
    parser.add_argument("--model", required=True)
    parser.add_argument("--model-digest", required=True)
    parser.add_argument("--attest-no-outcome-access", action="store_true")
    args = parser.parse_args()
    if not args.attest_no_outcome_access:
        raise SystemExit("refusing to freeze without --attest-no-outcome-access")
    protocol_path = args.output / "protocol.json"
    if protocol_path.exists():
        raise SystemExit(f"refusing to overwrite frozen protocol: {protocol_path}")
    args.output.mkdir(parents=True, exist_ok=True)
    tasks_path = args.output / "tasks.jsonl"
    arms_path = args.output / "arms.jsonl"
    write_jsonl(tasks_path, build_tasks())
    write_jsonl(arms_path, build_arms())
    protocol = O1Protocol(
        protocol_id="olympus-o1-v1",
        state="FROZEN_PRE_OUTCOME",
        frozen_at_utc=datetime.now(UTC).isoformat(),
        task_manifest=tasks_path.name,
        task_manifest_sha256=sha256_file(tasks_path),
        arm_manifest=arms_path.name,
        arm_manifest_sha256=sha256_file(arms_path),
        provider="ollama",
        provider_version=args.provider_version,
        model=args.model,
        model_digest=args.model_digest,
        context_tokens=2048,
        maximum_output_tokens=64,
        temperature=0.2,
        seeds=[17, 31, 47],
        primary_metric="exact_match",
        secondary_metrics=["category_accuracy", "brier", "consistency"],
        bootstrap_resamples=20_000,
        promotion_threshold=0.05,
        failure_threshold=0.0,
        raw_output_directory="runs/o1_v1",
        scorer_version="o1-exact-json-v1",
        no_outcome_access_attestation=True,
    )
    protocol_path.write_text(protocol.model_dump_json(indent=2) + "\n")
    print(protocol.model_dump_json(indent=2))


if __name__ == "__main__":
    main()
